using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Stok_Takip.Siparis
{
    public partial class Siparis_Durum : Form
    {
        public Siparis_Durum()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            
        }
        Modul_Sttok.MayaStokEntities db;
        Modul_Sttok.Siparis spr;
        private void Siparis_Durum_Load(object sender, EventArgs e)
        {
            db = new Modul_Sttok.MayaStokEntities();
            
            var list = db.Siparis.ToList();



        }

        

        private void btngoster_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {

        }
    }
}
