//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Modul_Sttok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int MusteriID { get; set; }
        public string Adi { get; set; }
        public string Adres { get; set; }
        public string Sehir { get; set; }
        public string PostaKodu { get; set; }
        public string Ulke { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Faks { get; set; }
    
        public virtual Siparis Siparis { get; set; }
    }
}
