//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Modul_Sttok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int id { get; set; }
        public string AdiSoyadi { get; set; }
        public string CepNo { get; set; }
        public string Gorev { get; set; }
        public string K_adi { get; set; }
        public string Sifre { get; set; }
        public string Yetki { get; set; }
    }
}
