//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Modul_Sttok
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int SiparisID { get; set; }
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<double> Genislik { get; set; }
        public Nullable<double> Yukseklik { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual Siparis Siparis { get; set; }
    }
}
