//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Modul_Sttok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int id { get; set; }
        public string Siparis_Kodu { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public string Musteriadi { get; set; }
        public string Urunadi { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<int> Adet { get; set; }
        public string goster { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual UretimBilgi UretimBilgi { get; set; }
    }
}
