//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Modul_Sttok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int id { get; set; }
        public string Stok_Kodu { get; set; }
        public string Stok_Adi { get; set; }
        public string Urun_Turu { get; set; }
        public string Adet { get; set; }
        public string Genislik { get; set; }
        public string Yukseklik { get; set; }
        public string Güncelle { get; set; }
    
        public virtual Tur Tur { get; set; }
    }
}
