//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Modul_Sttok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Üretim_Dikim
    {
        public int id { get; set; }
        public string Urun_Kod { get; set; }
        public string Musteri { get; set; }
        public string Siparis_Tipi { get; set; }
        public string Siparis_Miktari { get; set; }
        public string Urun_Adi { get; set; }
        public string Proses_Adi { get; set; }
        public string Genislik { get; set; }
        public string Yukseklik { get; set; }
        public string Kesim_Olcusu_Genislik { get; set; }
        public string Kesim_Olcusu_Yukseklik { get; set; }
        public string Kumas { get; set; }
        public string Biye { get; set; }
        public string Kılıf { get; set; }
        public string Kose_Etiketi { get; set; }
        public string Koruk { get; set; }
        public string Dolum_Sekli { get; set; }
        public Nullable<System.DateTime> Siparis_Giris_Tarihi { get; set; }
        public Nullable<System.DateTime> Kesim_Termin_Tarihi { get; set; }
        public string Acıklama { get; set; }
    }
}
